CREATE DATABASE IF NOT EXISTS wp CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

USE school_db;

CREATE TABLE IF NOT EXISTS schools (
    id_school INT AUTO_INCREMENT PRIMARY KEY,
    study_program VARCHAR(255) NOT NULL,
    school VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    date_time_added DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);